### PR TITLE
Add ot operator and optional statistics

### PR DESCRIPTION
**Pull request by rik2803**
Hi,

I was using your script and required some additional functionality:

- Check freshness for a prometheur metric returning an epoch timestamp
- Nagios statistics to be included in the output line

That's what this pull request contains.

Kind Regards,
Rik

### CODE REVIEW

**Comment by SuperQ** [comment]
Can you give an example use case for the older-than feature?  Wouldn't the query `time() - metric` give you what you want?

**Comment by rik2803** [comment]
You are absolutely right. I'm not a Prometheus expert and did not know this was possible. What about the statistics "feature"? (will make a new pull request for that)

**Comment by SuperQ** [comment]
The statistics feature is a good idea, feel free to update this PR or make a new one, whichever is easier for you.

FYI, you might consider following this workflow for fork-based pull requests in the future: https://gist.github.com/Chaser324/ce0505fbed06b947d962

This will help keep your fork clean and easy to update, as things get messy quickly if you commit to master on your own fork.

**Comment by beorn7** [comment]
Closing this PR. @rik2803 , looking forward to your new PR.

**Pull request closed without merging**
