### PR TITLE
Cleanup command variables

### PR DESCRIPTION
**Pull request by SuperQ**
* Use normal commands in `${PATH}` rather than variables.
* Add tests for `curl` and `jq` commands.

### CODE REVIEW

**Comment by beorn7** [comment]
How about going the other way, at least for `curl`, and make those variables take their value from environment variables so that users can inject flags for `curl` if needed? Cf. #16 .

**Comment by SuperQ** [comment]
I'd rather have a specific flag for `CURLOPTS`.  Dealing with detecting set / unset ENV vars in bash can be annoying.

**Comment by beorn7** [comment]
Fine with me. Could you add this in this PR? While clunky, the original setup is IMHO intended to set curl flags at a central location.

**Comment by SuperQ** [comment]
Done, added flag for `curl` options.

**Comment by beorn7** [comment]
:+1: Thanks.

**Pull request merged**
